spring:
  application:
    name: big-event

  datasource :
    url              : jdbc:mysql://localhost:3306/big_event
    username         : root
    password         : solowzl
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa        :
    show-sql    : true
    hibernate   :
      ddl-auto: update
    properties  :
      hibernate:
        format_sql: true

    open-in-view: true